# Generated by Django 3.2.17 on 2023-02-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
    ]
