# Generated by Django 3.2.17 on 2023-02-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230208_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
