# Generated by Django 3.2.17 on 2023-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('okushy', 'okushy')], max_length=20, null=True),
        ),
    ]
